### ISSUE TITLE
Consider deploying the prod build to GH pages

### ISSUE THREAD

**Issue by devabhixda** [aryamanpuri/portfolio#1]
https://dev.to/yuribenjamin/how-to-deploy-react-app-in-github-pages-2a1f

**Comment by aryamanpuri** [comment]
I tried to deploy with gh pages , but it shows Readme on deployement

**Comment by devabhixda** [comment]
You've actually pushed the source rather than the prod build, try following that guide it'll help you deploy a prod build

**Comment by devabhixda** [comment]
Good to see you got it working @aryamanpuri . https://github.com/aryamanpuri/portfolio/tree/gh-pages
